In [1]:
import numpy as np
from sklearn.metrics.pairwise  import euclidean_distances

# Problem 1

In [31]:
def linear_kernel(X1, X2):
    
    """
    Compute linear kernel between two set of feature vectors.
    The constant 1 is not appended to the x's.

    X1: n x m1 matrix, each of the m1 column is an n-dim feature vector.
    X2: n x m2 matrix, each of the m2 column is an n-dim feature vector.
    
    Note that m1 may not equal m2

    :return: if both m1 and m2 are 1, return linear kernel on the two vectors; else return a m1 x m2 kernel matrix K,
            where K(i,j)=linear kernel evaluated on column i from X1 and column j from X2.
    """
    #########################################
    shape_1 = X1.shape
    shape_2 = X2.shape
    K = np.zeros((shape_1[0], shape_2[1]))
    if shape_1[1] == 1 and shape_2[1] == 1:
        
        return np.dot(X1.T, X2)

    else:
        K = np.zeros((shape_1[0], shape_2[1]))
        for i in range(shape_1[0]):
            for j in range(shape_2[1]):
                    K[i,j] = np.dot(X1[:,i], X2[:,j])
        return K
    #########################################

In [32]:
X1 = np.array([[1, 2], [2, 4]]).T
X2 = np.array([[3, 4], [1, 2], [5, 6]]).T

linear_kernel(X1,X2)

array([[11.,  5., 17.],
       [22., 10., 34.]])

In [33]:
def Gaussian_kernel(X1, X2, sigma=1):
    """
    Compute Gaussian kernel between two set of feature vectors.
    
    The constant 1 is not appended to the x's.
    
    For your convenience, please use euclidean_distances.

    X1: n x m1 matrix, each of the m1 column is an n-dim feature vector.
    X2: n x m2 matrix, each of the m2 column is an n-dim feature vector.
    sigma: Gaussian variance (called bandwidth)

    Note that m1 may not equal m2

    :return: if both m1 and m2 are 1, return Gaussian kernel on the two vectors; else return a m1 x m2 kernel matrix K,
            where K(i,j)=Gaussian kernel evaluated on column i from X1 and column j from X2

    """
    #########################################
    shape_1 = X1.shape
    shape_2 = X2.shape

    if shape_1[1] == 1 and shape_2[1] == 1:
        return np.array([[np.exp( -(np.linalg.norm(X1[0,:] - X2[0,:])**2) )/(2*sigma**2)]])

        #Kernel = np.trace(K)

    else:
        K = np.zeros((shape_1[0], shape_2[1]))
        for i in range(shape_1[0]):
            for j in range(shape_2[1]):
                    K[i,j] = np.exp(-(euclidean_distances(np.array([X1[:,i]]),np.array([X2[:,j]]))**2)/(2*sigma**2))
        return K
    #########################################

In [34]:
X1 = np.array([[1, 2], [2, 4]]).T
X2 = np.array([[3, 4], [1, 2], [5, 6]]).T
#X1 = np.array([[1, 2]]).T
#X2 = np.array([[3, 4]]).T
Gaussian_kernel(X1, X2, 5)

array([[0.85214379, 1.        , 0.52729242],
       [0.98019867, 0.90483742, 0.77105159]])

In [35]:
def hinge_loss(z, y):
    """
    Compute the hinge loss on a set of training examples
    z: 1 x m vector, each entry is <w, x> + b (may be calculated using a kernel function)
    y: 1 x m label vector. Each entry is -1 or 1
    :return: 1 x m hinge losses over the m examples
    """
    #########################################
    shape_1 = max(z.shape)
    K = np.zeros((shape_1))
    for i in range(shape_1):
        K[i] = max(0, 1 - np.dot(y[:,i],z[i]))
    return K
    #########################################

In [36]:
X = np.array([[1, 2], [2, 4]]).T
y = np.array([[1, -1]])
w = np.array([1, 1])
b = -1

z = np.dot(w, X) + b

hinge_loss(z,y)

array([0., 6.])

In [37]:
np.dot(y[:,i],z[i])

IndexError: index 99 is out of bounds for axis 1 with size 2

In [ ]:
shape_1

2

In [ ]:
1 - np.dot(y[:,0],z[0])

array([-2])

In [ ]:
z

array([3, 6])

In [ ]:
z

array([3, 6])

In [ ]:
max(0, 1 - np.dot(y,z))

array([4])

In [ ]:
hinge_loss(z,y)

array([4., 0.])

In [ ]:
z

array([2, 5])

# Probelm 2

In [ ]:
def dual_objective_function(alpha, train_y, train_X, kernel_function, sigma):
      """
      Compute the dual objective function value.

      alpha: 1 x m learned Lagrangian multipliers (the dual variables).
      train_y: 1 x m labels (-1 or 1) of training data.
      train_X: n x m training feature matrix. n: number of features; m: number training examples.
      kernel_function: a kernel function implemented in problem1 (Python treats functions as objects).
      sigma: need to be provided when Gaussian kernel is used.
      :return: a scalar representing the dual objective function value at alpha
      Hint: refer to the objective function of Eq. (47).
            You can try to call kernel_function.__name__ to figure out which kernel are used.
      """
      #########################################
      if kernel_function.__name__ == 'linear_kernel':
            Kernels = linear_kernel(train_X, train_X)
            K = np.zeros((Kernels.shape[0], Kernels.shape[0]))

            for i in range(Kernels.shape[0]):
                  for j in range(Kernels.shape[1]):
                        K[i,j] = alpha[0][i]*alpha[0][j]*train_y[0][i]*train_y[0][j]*Kernels[i][j]
            
            return (np.sum(alpha) - 0.5*np.sum(K))

      elif kernel_function.__name__ == 'Gaussian_kernel':
            Kernels = Gaussian_kernel(train_X, train_X)
            K = np.zeros((Kernels.shape[0], Kernels.shape[0]))

            for i in range(Kernels.shape[0]):
                  for j in range(Kernels.shape[1]):
                        K[i,j] = alpha[0][i]*alpha[0][j]*train_y[0][i]*train_y[0][j]*Kernels[i][j]
            
            return (np.sum(alpha) - 0.5*np.sum(K))


    #########################################

In [ ]:
def primal_objective_function(alpha, train_y, train_X, b, C, kernel_function, sigma):
    """
    Compute the primal objective function value.
    When with linear kernel:
        The primal parameter w is recovered from the dual variable alpha.
    When with Gaussian kernel:
        Can't recover the primal parameter and kernel trick needs to be used to compute the primal objective function.

    alpha: 1 x m learned Lagrangian multipliers (the dual variables).
    train_y: 1 x m labels (-1 or 1) of training data.
    train_X: n x m training feature matrix.
    b: bias term
    C: regularization parameter of soft-SVM
    kernel_function: a kernel function implemented in problem1 (Python treats functions as objects).
    sigma: need to be provided when Gaussian kernel is used.

    :return: a scalar representing the primal objective function value at alpha
    Hint: you need to use kernel trick when come to Gaussian kernel. Refer to the derivation of the dual objective function Eq. (47) to check how to find
            1/2 ||w||^2 and the decision_function with kernel trick.
    """
    #########################################
    if kernel_function.__name__ == 'linear_kernel':
        #k = linear_kernel(train_X, train_X)
        w = np.array([np.sum(alpha[0][i]*train_y[0][i]*train_X[:,i]) for i in range(train_X.shape[0])])

        z = np.dot(w, train_X)+b
        loss = hinge_loss(z, train_y)

        return (0.5*np.linalg.norm(w)**2 + C*np.sum(loss))

    elif kernel_function.__name__ == 'Gaussian_kernel':
        K = Gaussian_kernel(train_X, train_X, sigma)
        Gram = np.zeros((K.shape[0], K.shape[0]))
        #wTx = [[]]
        for i in range(K.shape[0]):
                for j in range(K.shape[1]):
                    Gram[i,j] = alpha[0][i]*alpha[0][j]*train_y[0][i]*train_y[0][j]*K[i][j]

        uno = np.multiply(alpha, train_y)
        Gram = np.dot(K.T, K)
        uno_gram = np.dot(uno, Gram)
        done = np.dot(uno_gram, uno.T)

        front = 0.5*done
        z = sum(alpha*K)+b
        loss = hinge_loss(z,train_y)
        return (front + C*np.sum(loss))
    #########################################

In [ ]:
train_X = np.array([[1, 1], [-1, -1]]).T
train_y = np.array([[1, -1]])
alpha = np.array([[1, 1]])
b = -1
C = 10
sigma = None

w = np.array([np.sum(alpha[0][i]*train_y[0][i]*train_X[:,i]) for i in range(train_y.shape[1])])

z = np.dot(w, train_X)+b
loss = hinge_loss(z, train_y)

(0.5*np.dot(w,w) + C*np.sum(loss))
#primal_objective_function(alpha, train_y, train_X, b, C, linear_kernel, sigma)


4.0

In [ ]:
train_X = np.array([[1, 1], [-2, -2]]).T
train_y = np.array([[1, 1]])
alpha = np.array([[1, 1]])
b = -1
C = 10

sigma = None

w = np.array([np.sum(alpha[0][i]*train_y[0][i]*train_X[:,i]) for i in range(train_X.shape[0])])

z = np.dot(w, train_X)+b
loss = hinge_loss(z, train_y)

(0.5*np.linalg.norm(w)**2 + C*np.sum(loss))
#primal_objective_function(alpha, train_y, train_X, b, C, linear_kernel, sigma)

50.0

In [4]:
from problem2 import *
train_X = np.array([[1, 1], [-1, -1]]).T
train_y = np.array([[1, -1]])
alpha = np.array([[1, 1]])
b = -1
C = 10

sigma = 1

K = Gaussian_kernel(train_X, train_X)

# ||w||^2 
front = np.dot(np.dot(np.multiply(alpha, train_y), K), np.multiply(alpha, train_y).T) 
# y(wTx+b)
z = sum(np.dot(np.multiply(alpha,train_y),K))+b
# loss
loss = hinge_loss(z, train_y)

0.5*front + C*np.sum(loss)


array([[20.]])

In [5]:
K

array([[0.13533528, 0.13533528],
       [0.13533528, 0.13533528]])

In [ ]:
Gauss

array([[11.16484075]])

In [ ]:
alpha*train_y

array([[ 1, -1]])

In [ ]:
loss

array([1.01831564, 0.        ])

In [ ]:
z

array([ 0.98168436, -0.98168436])

In [ ]:
alpha*train_y*K

array([[ 1.        , -0.01831564],
       [ 0.01831564, -1.        ]])

In [ ]:
loss

array([0., 0.])

In [ ]:
z

array([ 0.01831564, -2.01831564])

In [ ]:
loss

array([0.98168436, 1.01831564])

In [ ]:
front 

array([[1.96336872]])

In [ ]:
front_1

array([[0.98168436]])

In [ ]:
z

array([[0.01831564, 0.01831564]])

In [ ]:
sum(alpha, K)+b

array([[1.        , 0.01831564],
       [0.01831564, 1.        ]])

In [ ]:
hinge

0

In [ ]:
front

array([[1.96336872]])

In [ ]:
11.1648407-front_1

array([[10.18315634]])

In [ ]:
sum(front)

array([0.98168436, 0.98168436])

In [ ]:
z

array([-1.01831564, -1.01831564])

In [ ]:
sum(loss)

2.018315638888734

In [ ]:
train_X = np.array([[1, 1], [-2, -2]]).T
train_y = np.array([[1, 1]])
alpha = np.array([[1, 1]])
b = -1
C = 10

sigma = 1
K = linear_kernel(train_X, train_X)

# ||w||^2 
front = np.dot(np.dot(np.multiply(alpha, train_y), K), np.multiply(alpha, train_y).T) 
# y(wTx+b)
z = sum(np.dot(np.multiply(alpha,train_y),K))+b
# loss
loss = hinge_loss(z, train_y)

0.5*front + C*np.sum(loss)



array([[41.]])

In [ ]:
(11.1648407 - front_1)/10

array([[1.01831563]])

In [ ]:
front

array([[2.00024682]])

In [ ]:
#z = sum(alpha*K) + b

z = front 
loss = hinge_loss(z,train_y)
front_1 + C*np.sum(loss)

In [ ]:
z

array([1.00012341, 1.00012341])

In [ ]:
loss

array([0., 0.])

In [ ]:
front

array([[1.00000000e+00, 1.23409804e-04],
       [1.23409804e-04, 1.00000000e+00]])

In [ ]:
K

array([[1.        , 0.01831564],
       [0.01831564, 1.        ]])

In [ ]:
(11.1648407 - front_1)

array([10.67399852, 10.67399852])

In [ ]:
np.sum(front)

1.9633687222225316

In [ ]:
front

array([[ 1.        , -0.01831564],
       [-0.01831564,  1.        ]])

In [ ]:
uno = np.multiply(alpha, train_y)
Gram = np.dot(K.T, K)
uno_gram = np.dot(uno, Gram)
done = np.dot(uno_gram, uno.T)

In [ ]:
train_X = np.array([[1, 1], [-2, -2]]).T
train_y = np.array([[1, 1]])
alpha = np.array([[1, 1]])
b = -1
C = 10
sigma = 1
K = Gaussian_kernel(train_X, train_X, sigma)
Gram = np.zeros((K.shape[0], K.shape[0]))
#wTx = [[]]
for i in range(K.shape[0]):
        for j in range(K.shape[1]):
            Gram[i,j] = alpha[0][i]*alpha[0][j]*train_y[0][i]*train_y[0][j]*K[i][j]



uno = np.multiply(alpha, train_y)
Gram = np.dot(K.T, K)
uno_gram = np.dot(uno, Gram)
done = np.dot(uno_gram, uno.T)

front = 0.5*done
z = sum(alpha*K)+b
loss = hinge_loss(z,train_y)
front + C*np.sum(loss)

array([[20.99777864]])

In [ ]:
def decision_function(alpha, train_y, train_X, b, kernel_function, sigma, test_X):
    """
    Compute the linear function <w, x> + b on examples in test_X, using the current SVM.

    alpha: 1 x m learned Lagrangian multipliers (the dual variables).
    train_y: 1 x m labels (-1 or 1) of training data.
    train_X: n x m training feature matrix.
    test_X: n x m2 test feature matrix.
    b: scalar, the bias term in SVM <w, x> + b.
    kernel_function: a kernel function implemented in problem1 (Python treats functions as objects).
    sigma: need to be provided when Gaussian kernel is used.

    :return: 1 x m2 vector <w, x> + b
    """
    #########################################
    if kernel_function.__name__ == 'linear_kernel':
        return np.dot(np.multiply(alpha,y), linear_kernel(test_X, train_X))+b
    elif kernel_function.__name__ == 'Gaussian_kernel':
        return np.dot(np.multiply(alpha,y), Gaussian_kernel(test_X, train_X, sigma))+b
    #########################################

In [ ]:
train_X = np.array([[1, 1], [-1, -1]]).T
train_y = np.array([[1, -1]])
test_X = np.array([[1, 1], [-1, -1]]).T
alpha = np.array([[1, 1]])
b = 4

sigma = None
sigma = 1

decision_function(alpha, train_y, train_X, b, linear_kernel, sigma, test_X)
decision_function(alpha, train_y, train_X, b, Gaussian_kernel, sigma, test_X)

array([[4.98168436, 3.01831564]])

In [ ]:
decision_function(alpha, train_y, train_X, b, Gaussian_kernel, sigma, test_X)

array([[8., 0.]])

# Problem 3

In [ ]:
from problem1 import *
from problem2 import *

import numpy as np

import copy

class SVMModel():
    """
    The class containing information about the SVM model, including parameters, data, and hyperparameters.

    DONT CHANGE THIS DEFINITION!
    """
    def __init__(self, train_X, train_y, C, kernel_function, sigma=1):
        """
            train_X: n x m training feature matrix. n: number of features; m: number training examples.
            train_y: 1 x m labels (-1 or 1) of training data.
            C: a positive scalar
            kernel_function: a kernel function implemented in problem1 (Python treats functions as objects).
            sigma: need to be provided when Gaussian kernel is used.
        """
        # data
        self.train_X = train_X
        self.train_y = train_y
        self.n, self.m = train_X.shape

        # hyper-parameters
        self.C = C
        self.kernel_func = kernel_function
        self.sigma = sigma

        # parameters
        self.alpha = np.zeros((1, self.m))
        self.b = 0

def train(model, max_iters = 10, record_every = 1, max_passes = 1, tol=1e-6):
    """
    SMO training of SVM
    model: an SVMModel
    max_iters: how many iterations of optimization
    record_every: record intermediate dual and primal objective values and models every record_every iterations
    max_passes: each iteration can have maximally max_passes without change any alpha, used in the SMO alpha selection.
    tol: numerical tolerance (exact equality of two floating numbers may be impossible).
    :return: 4 lists (of iteration numbers, dual objectives, primal objectives, and models)
    Hint: refer to subsection 3.5 "SMO" in notes.
    """
    #########################################
    ## INSERT YOUR CODE HERE
    #########################################

In [ ]:
train_X = np.array([[1, 1], [-1, -1]]).T
train_y = np.array([[1, -1]])
C = 10
sigma = 1
tol = 1e-6

# Instantiate model
model = SVMModel(train_X, train_y, C, linear_kernel, sigma)
max_iters = 10
record_every = 1


# Creating the lists
iter_num = []
duals = []
primals = []
models = []

# set dual variables to zero
#alpha = np.zeros(model.train_y.shape)
#b = 0

# begin iteration
for t in range(max_iters):
    passes = 0
    while passes < max_iters:
        num_changes = 0
        for i in range(model.train_X.shape[0]):
            if model.alpha[0][i] < 0 or model.alpha[0][i] > model.C or np.dot(model.alpha, model.train_y.T) != 0: 
                # Random initialize
                j = np.random.randint(low = 0, high = model.train_X.shape[0])
                alpha_j = model.alpha[0][j]

                # Upper and Lower Bounds
                H = min(model.C, model.C - (model.alpha[0][0] - model.alpha[0][1]))
                L = max(0, -(model.alpha[0][0] - model.alpha[0][1]))

                # Kernel Used
                if model.kernel_func.__name__ == 'linear_kernel':
                    K = linear_kernel(model.train_X, model.train_X)
                elif model.kernel_func.__name__ == 'Gaussian_kernel':
                    K = Gaussian_kernel(model.train_X, model.train_X)

                #g vector with g_1 and g_2 inside for efficiency
                g_vec = np.dot(np.multiply(model.alpha,model.train_y), K) + b

                # alpha_2 value
                alpha_new = alpha_j + ((y[0][1]*(g_vec[0][0], - y[0][0] - g_vec[0][1]+y[0][1]))
                                        /(K[0][0] + K[1][1] - 2*K[1][2]))

                # alpha_2 classification
                if alpha_new > H:
                    alpha_new_clipped = H

                elif alpha_new < L:
                    alpha_new_clipped = L

                else: 
                    alpha_new_clipped = alpha_new

                # Stopping if not meaningful change
                if np.abs(alpha_new_clipped-alpha_j) < tol:

                    continue

                # Getting alpha_1 if meaningful change
                alpha_1_new = model.alpha[0][0] + (model.train_y[0][0]*model.train_y[0][1]) * (alpha_j - alpha_new_clipped)

                # b primal
                # E vector (E_1, E_2)
                E = g_vec - model.train_y
                b1 = model.b - E[0][0] - model.train_y[0][0]*(alpha_1_new - model.alpha[0][0])*K[0][0] - model.train_y[0][1]*(alpha_new_clipped - alpha_j)*K[0][1]
                b2 = model.b - E[0][1] - model.train_y[0][0]*(alpha_1_new - model.alpha[0][0])*K[0][1] - model.train_y[0][1]*(alpha_new_clipped - alpha_j)*K[1][1]

                # update model values
                # alphas
                model.alpha[0][0] = alpha_1_new
                model.alpha[0][1] = alpha_new_clipped

                # b primal
                if 0 < model.alpha[0][0] < model.C:
                    b_new = b1
                
                elif 0 < model.alpha[0][1] < model.C:
                    b_new = b2

                else:
                    b_new = (b1 + b2)/2

                model.b = b_new
                num_changes += 1
        
        if num_changes == 0:
            passes +=1
        else:
            passes = 0
    iter_num.append(t)
    duals.append(dual_objective_function(model.alpha, model.train_y, model.train_X, model.kernel_func, model.sigma))
    primals.append(primal_objective_function(model.alpha, model.train_y, model.train_X, model.b, model.C, model.kernel_func, model.sigma))
    models.append(vars(model))






# Answer = [1, -1]

In [ ]:
from problem1 import*
from problem2 import*



train_X = np.array([[1, 1], [-1, -1]]).T
train_y = np.array([[1, -1]])
C = 10
sigma = 1

# Instantiate model
model = SVMModel(train_X, train_y, C, linear_kernel, sigma)
model.alpha[0, 0] = 1
model.alpha[0, 1] = 1
model.b = 1
#K = np.zeros((model.train_X.shape[0]))
#for i in range(model.train_X.shape[0]):
    #K[i] = np.dot(np.array([model.train_X[:,i]]), model.train_X)
#K = linear_kernel(model.train_X, model.train_X)
vals = decision_function(model.alpha, model.train_y, model.train_X, model.b, model.kernel_func, model.sigma, model.train_X)
assignments = np.array([1 if i > 0 else -1 for i in vals[0]])

In [ ]:
assignments

array([ 1, -1])

In [ ]:
np.dot(np.array([model.train_X[:,0]]), model.train_X)

array([[ 2, -2]])

In [ ]:
model.train_X

In [ ]:
K

array([[ 2., -2.],
       [-2.,  2.]])

In [ ]:
model.alpha

array([[1., 1.]])

In [ ]:
np.array([model.train_X[:,i]])

array([[1, 1]])

In [ ]:
np.multiply(model.alpha, model.train_y)

array([[ 1., -1.]])

In [ ]:
K

array([[ 2., -2.],
       [-2.,  2.]])

In [ ]:
shape_1 = model.train_X.shape
shape_2 = model.train_X.shape
K = np.zeros((shape_1[0], shape_2[1]))
for i in range(shape_1[0]):
    for j in range(shape_2[1]):
            K[i,j] = np.dot(model.train_X[:,i], model.train_X[:,j])

In [ ]:
shape_1

(2, 2)

In [ ]:
shape_2

(2, 2)

In [ ]:
K

array([[ 2., -2.],
       [-2.,  2.]])

In [ ]:
shape_1 = X1.shape
shape_2 = X2.shape
K = np.zeros((shape_1[0], shape_2[1]))
if shape_1[1] == 1 and shape_2[1] == 1:
    
    return np.dot(X1.T, X2)

else:
    K = np.zeros((shape_1[0], shape_2[1]))
    for i in range(shape_1[0]):
        for j in range(shape_2[1]):
                K[i,j] = np.dot(X1[:,i], X2[:,j])
    rK

In [ ]:
K

array([[0., 0.],
       [0., 0.]])

In [ ]:
model.alpha[0][0]*model.train_y[0][0]*K[0][0] + model.alpha[0][1]*model.train_y[0][1]*K[0][1]

0.0

In [ ]:
model.alpha[0][0]*model.train_y[0][0]*K[1][0] + model.alpha[0][1]*model.train_y[0][1]*K[1][1]

0.0

In [ ]:
K

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.multiply(model.alpha, model.train_y)

array([[ 1., -1.]])

In [ ]:
K

array([[0., 0.],
       [0., 0.]])

In [ ]:
iter_num

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
duals

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [ ]:
primals

[20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0]

In [ ]:
models

[{'train_X': array([[ 1, -1],
         [ 1, -1]]),
  'train_y': array([[ 1, -1]]),
  'n': 2,
  'm': 2,
  'C': 10,
  'kernel_func': <function problem1.linear_kernel(X1, X2)>,
  'sigma': 1,
  'alpha': array([[0., 0.]]),
  'b': 0},
 {'train_X': array([[ 1, -1],
         [ 1, -1]]),
  'train_y': array([[ 1, -1]]),
  'n': 2,
  'm': 2,
  'C': 10,
  'kernel_func': <function problem1.linear_kernel(X1, X2)>,
  'sigma': 1,
  'alpha': array([[0., 0.]]),
  'b': 0},
 {'train_X': array([[ 1, -1],
         [ 1, -1]]),
  'train_y': array([[ 1, -1]]),
  'n': 2,
  'm': 2,
  'C': 10,
  'kernel_func': <function problem1.linear_kernel(X1, X2)>,
  'sigma': 1,
  'alpha': array([[0., 0.]]),
  'b': 0},
 {'train_X': array([[ 1, -1],
         [ 1, -1]]),
  'train_y': array([[ 1, -1]]),
  'n': 2,
  'm': 2,
  'C': 10,
  'kernel_func': <function problem1.linear_kernel(X1, X2)>,
  'sigma': 1,
  'alpha': array([[0., 0.]]),
  'b': 0},
 {'train_X': array([[ 1, -1],
         [ 1, -1]]),
  'train_y': array([[ 1, -1]]),
 

In [ ]:
K = linear_kernel(model.train_X, model.train_X)
g_vec = np.dot(np.multiply(model.alpha,model.train_y), K) + b

In [ ]:
model.train_y

array([[ 1, -1]])

In [ ]:
g_vec - model.train_y

array([[-1.,  1.]])

In [ ]:
np.dot(alpha, model.train_y.T)

array([[0.]])

In [ ]:
alpha

array([[0., 0.]])

In [ ]:
model.train_y

array([[ 1, -1]])

In [ ]:
hhh = model.train_X.shape[0]

samp_idx = np.random.randint(low = 0, high = model.train_X.shape[0])

In [ ]:
hhh

range(0, 2)

In [ ]:
samp_idx

0

In [ ]:
import pandas as pd

blob = pd.read_pickle(r'C:\MFE\MFE Sem 3\CSE 426\CSE_426\Project 2\data\blobs_data.pkl')

In [ ]:
blob['tr_X'].shape

(2, 100)

In [41]:
X1 = np.array([[1, 2], [2, 4]]).T
X2 = np.array([[3, 4], [1, 2], [5, 6]]).T
sigma = 5
np.exp(-(euclidean_distances(X1,X2)**2)/(2*sigma**2))

In [46]:
X2 = np.array([[1, 2], [2, 4]]).T
X1 = np.array([[3, 4], [1, 2], [5, 6]]).T
sigma = 5
np.exp(-(euclidean_distances(X1,X2.T)**2)/(2*sigma**2))

array([[0.85214379, 0.98019867],
       [1.        , 0.90483742],
       [0.52729242, 0.77105159]])

In [47]:
train_X = np.array([[1, 1], [-1, -1]]).T
train_y = np.array([[1, -1]])
alpha = np.array([[1, 1]])
b = -1
C = 10

In [50]:
K = linear_kernel(train_X, train_X)



In [53]:
np.multiply(alpha, train_y)

array([[ 1, -1]])

In [55]:
# ||w||^2 
front = np.dot(np.dot(np.multiply(alpha, train_y), K), np.multiply(alpha, train_y).T) 
# y(wTx+b)
z = sum(np.dot(np.multiply(alpha,train_y),K))+b
# loss
loss = hinge_loss(z, train_y)

Lin = 0.5*front + C*np.sum(loss)

Lin

array([[4.]])

In [27]:
X1.shape

(2, 2)

In [28]:
X2.shape

(2, 3)

In [29]:
np.dot(X1.T, X2) # linear Kernel

array([[11,  5, 17],
       [22, 10, 34]])

In [37]:
X1 = np.array([[1, 2]]).T
X2 = np.array([[3, 4]]).T
sigma = 1

In [40]:
np.exp(-(euclidean_distances(X1.T,X2.T)**2)/(2*sigma**2))

array([[0.01831564]])

In [ ]:
np.exp(-(euclidean_distances(np.array([X1]),np.array([X2]))**2)/(2*sigma**2))

In [1]:
'''
    Problem 4: Train an SVM using SMO, on 3 simulated datasets (blobs, circles, and two moons) with 2 kernels (Linear and Gaussian)
'''

from problem1 import *
from problem2 import *
from problem3 import *

from sklearn.datasets import make_blobs, make_circles, make_moons
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

import pickle
import numpy as np

def generate_dataset(n_samples, distribution_name):
    if distribution_name == 'blobs':
        X_train, y = make_blobs(n_samples, centers=2, n_features=2, random_state=1)
    elif distribution_name == 'circles':
        X_train, y = make_circles(n_samples, noise=0.01, factor=0.1, random_state=1)
    else:
        X_train, y = make_moons(n_samples, noise=0.01, random_state=1)
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train, y)
    X_train_scaled = X_train_scaled.T
    y[y == 0] = -1
    print('y.shape', y.shape)
    return X_train_scaled, np.expand_dims(y, axis=0)


def train_test_SVM(**kwargs):
    """
    Don't change this function.
    :param kwargs:
    :return:
    """
    # Instantiate a SVM model
    model = SVMModel(kwargs['Training X'],
                     kwargs['Training y'],
                     kwargs['C'],
                     kwargs['kernel'],
                     kwargs['sigma'])

    # call the train function from problem3.
    iter_num, duals, primals, models = train(model, kwargs['max_iters'], kwargs['record_every'])

    for it, d, p in zip(iter_num, duals, primals):
        print('iterations = {}: dual objective value = {}, primal objective value = {}'.format(it, d, p))

    # save your trained model to file
    with open('C:/MFE/MFE Sem 3/CSE 426/CSE_426/Project 2/data/trained_model_{}_{}.pkl'.format(kwargs['distribution'], kwargs['kernel'].__name__), 'wb') as f:
        pickle.dump(model, f)

    # call the predict function from problem3.
    predicted_y = predict(model, kwargs['Test X'])

    print('Test accuracy = {}'.format(accuracy_score(np.array(kwargs['Test y']).flatten(), np.array(predicted_y).flatten())))

# --------------------------


In [2]:
if __name__ == "__main__":

    C = 1.0
    sigma = 0.1

    n_samples = 100
    for dist in ['blobs', 'circles', 'moons']:
        print ('\n\n========Data distribution = {}========'.format(dist))
        tr_X, tr_y = generate_dataset(n_samples, dist)
        te_X, te_y = generate_dataset(n_samples, dist)
        
        with open('C:/MFE/MFE Sem 3/CSE 426/CSE_426/Project 2/data/' + dist + '_data.pkl', 'wb') as f:
             pickle.dump({'tr_X':tr_X,
                          'tr_y':tr_y,
                          'te_X':te_X,
                          'te_y':te_y}, f)
        with open('C:/MFE/MFE Sem 3/CSE 426/CSE_426/Project 2/data/' + dist + '_data.pkl', 'rb') as f:
            data_dict = pickle.load(f)
        tr_X = data_dict['tr_X']
        tr_y = data_dict['tr_y']
        te_X = data_dict['te_X']
        te_y = data_dict['te_y']

        for kernel in [linear_kernel, Gaussian_kernel]:
        # for kernel in [Gaussian_kernel]:

            print ('========using kernel {}========'.format(kernel.__name__))
            kwargs = {'distribution': dist,
                      'Training X': tr_X,
                      'Training y': tr_y,
                      'Test X': te_X,
                      'Test y': te_y,
                      'C': C,
                      'sigma': sigma,
                      'kernel': kernel,
                      'max_iters': 10,
                      'record_every': 1
                      }

            train_test_SVM(**kwargs)




========Data distribution = blobs========
========using kernel linear_kernel========


ValueError: shapes (1,100) and (2,100) not aligned: 100 (dim 1) != 2 (dim 0)

In [23]:
import pandas as pd

blob = pd.read_pickle(r'C:\MFE\MFE Sem 3\CSE 426\CSE_426\Project 2\data\blobs_data.pkl')

In [4]:
blob.keys()

dict_keys(['tr_X', 'tr_y', 'te_X', 'te_y'])

In [18]:
X_train, y = make_blobs(n_samples, centers=2, n_features=2, random_state=1)

In [20]:
X_train.shape

(100, 2)

In [22]:
y.shape

(100,)

In [5]:
model = SVMModel(blob['tr_X'], blob['tr_y'], 1, linear_kernel, 1)

In [6]:
K = linear_kernel(np.array([model.train_X.T[:,0]]), np.array([model.train_X.T[:,1]]))

In [52]:
g_vec = np.dot(np.multiply(model.alpha,model.train_y), K.T) + model.b

In [46]:
max_iters = 10
record_every = 1
max_passes = 1
tol=1e-6

iter_num = []
duals = []
primals = []
models = []

# set dual variables to zero
#alpha = np.zeros(model.train_y.shape)
#b = 0

# begin iteration
for t in range(max_iters):
    passes = 0
    while passes < max_passes:
        num_changes = 0
        for i in range(model.m):
            if model.alpha[0][i] < 0 or model.alpha[0][i] > model.C or np.dot(model.alpha, model.train_y.T) != 0 or : 
                # Random initialize
                j = np.random.randint(low = 0, high = model.m)
                alpha_j = model.alpha[0][j]

                # Upper and Lower Bounds
                H = min(model.C, model.C - (model.alpha[0][i] - model.alpha[0][j]))
                L = max(0, -(model.alpha[0][i] - model.alpha[0][j]))

                # Kernel Used
                if model.kernel_func.__name__ == 'linear_kernel':
                    K = linear_kernel(model.train_X, model.train_X)
                elif model.kernel_func.__name__ == 'Gaussian_kernel':
                    K = Gaussian_kernel(model.train_X, model.train_X)
                print(K)
                #g vector with g_1 and g_2 inside for efficiency
                g_vec = np.dot(np.multiply(model.alpha,model.train_y), K) + model.b

                # alpha_2 value
                alpha_new = alpha_j + ((model.train_y[0][i]*(g_vec[0][0], - model.train_y[0][i] - g_vec[0][1] + model.train_y[0][j]))
                                        /(K[0][0] + K[1][1] - 2*K[0][2]))

                # alpha_2 classification
                if alpha_new > H:
                    alpha_new_clipped = H

                elif alpha_new < L:
                    alpha_new_clipped = L

                else: 
                    alpha_new_clipped = alpha_new

                # Stopping if not meaningful change
                if np.abs(alpha_new_clipped-alpha_j) < tol:

                    continue

                # Getting alpha_1 if meaningful change
                alpha_1_new = model.alpha[0][0] + (model.train_y[0][0]*model.train_y[0][1]) * (alpha_j - alpha_new_clipped)

                # b primal
                # E vector (E_1, E_2)
                E = g_vec - model.train_y
                b1 = model.b - E[0][0] - model.train_y[0][0]*(alpha_1_new - model.alpha[0][0])*K[0][0] - model.train_y[0][1]*(alpha_new_clipped - alpha_j)*K[0][1]
                b2 = model.b - E[0][1] - model.train_y[0][0]*(alpha_1_new - model.alpha[0][0])*K[0][1] - model.train_y[0][1]*(alpha_new_clipped - alpha_j)*K[1][1]

                # update model values
                # alphas
                model.alpha[0][0] = alpha_1_new
                model.alpha[0][1] = alpha_new_clipped

                # b primal
                if 0 < model.alpha[0][0] < model.C:
                    b_new = b1
                
                elif 0 < model.alpha[0][1] < model.C:
                    b_new = b2

                else:
                    b_new = (b1 + b2)/2

                model.b = b_new
                num_changes += 1
        
        if num_changes == 0:
            passes +=1
        else:
            passes = 0
    if t == 0:
        iter_num.append(t)
        duals.append(dual_objective_function(model.alpha, model.train_y, model.train_X, model.kernel_func, model.sigma))
        primals.append(primal_objective_function(model.alpha, model.train_y, model.train_X, model.b, model.C, model.kernel_func, model.sigma))
        models.append(vars(model))
    elif t - iter_num[-1] == record_every:
        iter_num.append(t)
        duals.append(dual_objective_function(model.alpha, model.train_y, model.train_X, model.kernel_func, model.sigma))
        primals.append(primal_objective_function(model.alpha, model.train_y, model.train_X, model.b, model.C, model.kernel_func, model.sigma))
        models.append(vars(model))
#return iter_num, duals, primals, models
#########################################

In [8]:
model.train_X.shape

(2, 100)