nosetests -v test1.py

nosetests -v test2.py


In [1]:
import numpy as np
from scipy.special import logsumexp
from scipy.special import xlogy, xlog1py
from problem1 import *
from problem2 import *
import pandas as pd
import pickle

In [2]:
X = np.asmatrix(np.array([[1,1], [-1,-1]]))
Y = np.asmatrix(np.array([[1, 0, 0], [0, 1, 0]])).T
input_dim = 2
num_classes = 3
# make a tiny network
dimensions = [input_dim, 2, num_classes]

activation_funcs = {1:Tanh, 2:Softmax}
loss_func = CrossEntropyLoss
nn = NN(dimensions, activation_funcs, loss_func, rand_seed = 42)
output = nn.forward(X)
nn.backward(Y)


({2: matrix([[-0.06333099,  0.08278244],
          [-0.04217778,  0.05513225],
          [ 0.10550877, -0.13791469]]),
  1: matrix([[-0.1251907 ,  0.1251907 ],
          [ 0.04156961, -0.04156961]])},
 {2: matrix([[-0.15040323],
          [-0.10016699],
          [ 0.25057022]]),
  1: matrix([[-0.1251907 ],
          [ 0.04156961]])})

In [162]:
X = np.asmatrix(np.array([[1, 1], [-1, -1]])).T
Y = np.asmatrix(np.array([[1, 0, 0], [0, 1, 0]])).T
input_dim = 2
num_classes = 3
# make a tiny network
dimensions = [input_dim, 2, num_classes]

activation_funcs = {1: Tanh, 2: Softmax}
loss_func = CrossEntropyLoss
nn = NN(dimensions, activation_funcs, loss_func, rand_seed=42)

output = nn.forward(X)
nn.backward(Y)
#nn.update_parameters(lr=0.1, weight_decay=0.01)
lr=0.1
weight_decay=0.01

In [40]:
output

matrix([[0.20510984, 0.47948746],
        [0.48561002, 0.20252382],
        [0.30928014, 0.31798872]])

In [41]:
nn.dW

{2: matrix([[-0.15813148, -0.58064749],
         [ 0.15921209,  0.5846154 ],
         [-0.00108061, -0.00396791]]),
 1: matrix([[0.69106193, 0.69106193],
         [0.06855901, 0.06855901]])}

In [163]:
for l in reversed(range(nn.num_layers)):
    #W = np.array(nn.W[l+1] - lr*np.average(nn.dW[l+1], axis = 0) - weight_decay*lr*nn.W[l+1])
    B = nn.W[l+1].shape[1]
    averages = []

    #W = nn.W[l+1] - lr*(1/B)*np.sum(nn.dW[l+1], axis = 1) - lr*weight_decay*nn.W[l+1]
    #W = nn.W[l+1] - lr*weight_decay*nn.W[l+1]
    #W = np.array(nn.W[l+1] - lr*np.average(nn.dW[l+1], axis = 1) - weight_decay*lr*nn.W[l+1])
    W = np.asarray(nn.W[l+1] - (lr*nn.dW[l+1]+weight_decay*nn.W[l+1]))
    b = np.asarray(nn.b[l+1] - lr*np.average(nn.db[l+1], axis = 1))
    
    nn.W[l+1] = W
    nn.b[l+1] = b

In [ ]:
for l in reversed(range(self.num_layers)):
    #W = np.array(self.W[l+1] - lr*np.average(self.dW[l+1], axis = 0) - weight_decay*lr*self.W[l+1])
    B = self.W[l+1].shape[1]
    averages = []

    #W = self.W[l+1] - lr*(1/B)*np.sum(self.dW[l+1], axis = 1) - lr*weight_decay*self.W[l+1]
    #W = self.W[l+1] - lr*weight_decay*self.W[l+1]
    #W = np.array(self.W[l+1] - lr*np.average(self.dW[l+1], axis = 1) - weight_decay*lr*self.W[l+1])
    W = np.asanyarray(self.W[l+1] - (lr*self.dW[l+1]+weight_decay*self.W[l+1]))
    b = np.asanyarray(self.b[l+1] - lr*np.average(self.db[l+1], axis = 1))
    
    self.W[l+1] = W
    self.b[l+1] = b

In [147]:
C = np.array([[-0.13079753, -0.08853565],
                                          [ 0.97287285, 0.42205312],
                                          [-0.2938444, 0.34011044]])

In [148]:
C

array([[-0.13079753, -0.08853565],
       [ 0.97287285,  0.42205312],
       [-0.2938444 ,  0.34011044]])

In [41]:
with open('../data/X_train.pkl', 'rb') as f:
    X_train = pickle.load(f)
    X_train.reshape(-1, )
with open('../data/Y_train.pkl', 'rb') as f:
    Y_train = pickle.load(f)
with open('../data/X_test.pkl', 'rb') as f:
    X_test = pickle.load(f)
with open('../data/Y_test.pkl', 'rb') as f:
    Y_test = pickle.load(f)

num_classes = len(np.unique(Y_train))
input_dim, n_samples = X_train.shape

print(f'num_classes = {num_classes}')
print(f'num_pixels = {input_dim}')
print(f'num_training_samples = {n_samples}')

tr_y_multi_class = np.zeros((num_classes, n_samples))
for i in range(num_classes):
    tr_y_multi_class[i, np.where(Y_train == i)] = 1
Y_train = np.asmatrix(tr_y_multi_class)

input_dim, n_samples = X_test.shape
te_y_multi_class = np.zeros((num_classes, n_samples))
for i in range(num_classes):
    te_y_multi_class[i, np.where(Y_test == i)] = 1
Y_test = np.asmatrix(te_y_multi_class)


num_classes = 10
num_pixels = 784
num_training_samples = 60000


In [45]:
input_dim, n_samples = X_train.shape
num_classes = Y_train.shape[0]

# input -> hidden -> output
# you're encouraged to explore other architectures with more or less number of layers
# Is more layers the better?
# Will ReLU work better than Sigmoid/Tanh?
dimensions = [input_dim, 128, 64, num_classes]
activation_funcs = {1:ReLU, 2:ReLU, 3:Softmax}
loss_func = CrossEntropyLoss

nn = NN(dimensions, activation_funcs, loss_func)

In [30]:
Y_train.shape

(10, 60000)

In [46]:
idx_total = np.array([i for i in range(X_train.shape[1])])
idx_chosen = np.random.choice(idx_total, 1024)
idx_chosen

array([15232, 40201, 37250, ..., 13261,  8494, 58140])

In [54]:
batch_X = np.asmatrix(X_train[:, idx_chosen])
batch_Y = Y_train[:, idx_chosen]

In [61]:
np.asmatrix(batch_X)

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [57]:
nn.forward(batch_X)

matrix([[1.32562086e-099, 1.62170660e-058, 8.66843936e-061, ...,
         3.97959024e-083, 1.17796324e-051, 1.14316455e-047],
        [3.25118357e-019, 1.00000000e+000, 2.16910576e-009, ...,
         2.25130891e-051, 9.99999997e-001, 3.04296436e-014],
        [1.26102992e-030, 4.61455183e-052, 9.60313492e-049, ...,
         9.99973574e-001, 1.23249538e-018, 1.45667890e-012],
        ...,
        [2.31395348e-044, 4.04969844e-026, 6.63016359e-015, ...,
         2.64259630e-005, 2.52587478e-009, 2.36281845e-020],
        [1.73090760e-053, 2.60450684e-040, 1.79527541e-046, ...,
         1.75254097e-016, 3.08228977e-039, 1.34272665e-034],
        [6.48338638e-082, 8.53812240e-078, 7.67791386e-098, ...,
         5.98613822e-144, 1.71472863e-054, 6.77829384e-065]])

In [59]:
nn.W

{1: array([[ 0.01281462, -0.01681995, -0.04801625, ..., -0.04156526,
         -0.08882439,  0.05631045],
        [ 0.05134242, -0.00932368, -0.07158581, ..., -0.02925459,
          0.05333309, -0.03275151],
        [-0.05782082,  0.01960143, -0.01658495, ...,  0.03188254,
          0.00721184,  0.02622417],
        ...,
        [-0.02580748,  0.01502379, -0.01559611, ..., -0.0575529 ,
         -0.05530085,  0.02032981],
        [ 0.02487779, -0.00972895, -0.00882909, ...,  0.00462062,
          0.01636385,  0.01458454],
        [-0.03934571, -0.04404587, -0.04226197, ..., -0.08675325,
          0.05056021, -0.02665768]]),
 2: array([[ 0.04271246,  0.07672326,  0.07417713, ..., -0.08608501,
          0.10894244,  0.07180132],
        [ 0.00396325,  0.00609534, -0.03719781, ..., -0.05618506,
          0.1892711 ,  0.00906096],
        [ 0.16921743, -0.01914642, -0.04710386, ...,  0.03430362,
          0.03317311,  0.01530734],
        ...,
        [ 0.00655572,  0.07089214, -0.17464854, 

In [117]:
X = np.asmatrix(np.array([[1, 1], [-1, -1]])).T
y = 1
# Y = np.asmatrix(np.array([[1, 0, 0], [0, 1, 0]])).T
input_dim = 2
num_classes = 3
# make a tiny network
dimensions = [input_dim, 2, num_classes]

activation_funcs = {1: Tanh, 2: Softmax}
loss_func = CrossEntropyLoss
nn = NN(dimensions, activation_funcs, loss_func, rand_seed=42)

#feature_map = nn.explain(X, y)

nn.forward(X)

matrix([[0.20510984, 0.47948746],
        [0.48561002, 0.20252382],
        [0.30928014, 0.31798872]])

In [136]:
d_zz = {}
for l in reversed(range(nn.num_layers)):
    if l == nn.num_layers - 1:
        W_c = np.array([nn.W[l+1][y,:]])
        d_zz[l]= np.multiply(W_c.T, nn.g[l].gradient(nn.Z[l]))
    elif 0 < l < nn.num_layers - 1:
        d_zz[l] = np.multiply(nn.W[l+1].T @ d_zz[l+1], nn.g[l].gradient(nn.Z[l]))
    else:
        d_zz[l] = nn.W[l+1].T @ d_zz[l+1]


#nn.W[1].T @ d_zz[2]


In [ ]:
d_zz = {}
for l in reversed(range(self.num_layers)):
    if l == self.num_layers - 1:
        W_c = np.array([self.W[l+1][y,:]])
        d_zz[l]= np.multiply(W_c.T, self.g[l].gradient(self.Z[l]))
    elif 0 < l < self.num_layers - 1:
        d_zz[l] = np.multiply(self.W[l+1].T @ d_zz[l+1], self.g[l].gradient(self.Z[l]))
    else:
        d_zz[l] = self.W[l+1].T @ d_zz[l+1]


#self.W[1].T @ d_zz[2]

In [137]:
d_zz

{1: matrix([[0.93726829, 0.93726829],
         [0.08231709, 0.08231709]]),
 0: matrix([[ 0.36689668,  0.36689668],
         [-0.00298354, -0.00298354]])}

In [ ]:
d_zz_init = np.multiply(np.array([nn.W[2][y,:]]).T, 

In [120]:
np.array([nn.W[2][:,y]])

array([[-0.14808121,  0.48536834,  0.3431451 ]])

In [128]:
nn.W[1].T@d_zz[2]

matrix([[ 0.36689668,  0.36689668],
        [-0.00298354, -0.00298354]])

In [123]:
d_zz

{2: matrix([[0.93726829, 0.93726829],
         [0.08231709, 0.08231709]]),
 1: matrix([[ 0.34430002,  0.34430002],
         [-0.000506  , -0.000506  ]])}

In [115]:
nn.g[1].gradient(nn.Z[1])

matrix([[0.93841139, 0.93841139],
        [0.16959715, 0.16959715]])

In [112]:
W_c

array([[0.99878188, 0.48536834]])

In [105]:
nn.W[l+1][y,:]

array([0.45798496, 1.07694474])

In [103]:
d_zz

{2: matrix([[0.93726829, 0.45547518],
         [0.16939056, 0.08231709]]),
 1: matrix([[0.38172231, 0.18550189],
         [0.01539769, 0.00748267]])}

In [96]:
nn.g[1].gradient(nn.Z[1])

matrix([[0.93841139, 0.93841139],
        [0.16959715, 0.16959715]])

In [98]:
nn.W[2].T @ d_zz[2]

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [99]:
d_zz[2]

matrix([[0.93726829, 0.45547518],
        [0.16939056, 0.08231709]])

In [89]:
nn.W[1].T

array([[ 0.35122995,  0.45798496],
       [-0.09776762,  1.07694474]])

In [91]:
d_zz

{2: matrix([[0.93726829, 0.45547518],
         [0.16939056, 0.08231709]])}

In [76]:
nn.g

{1: problem1.Tanh, 2: problem1.Softmax}

In [75]:
nn.W

{1: array([[ 0.35122995, -0.09776762],
        [ 0.45798496,  1.07694474]]),
 2: array([[-0.1480916 , -0.14808121],
        [ 0.99878188,  0.48536834],
        [-0.29692167,  0.3431451 ]])}

In [74]:
np.multiply(nn.W[2][:,y].T, nn.loss_func.gradient()  )

array([-0.14808121,  0.48536834,  0.3431451 ])

In [ ]:
nn.W[2].T*

In [ ]:
assert type(feature_map) == np.matrixlib.defmatrix.matrix
assert np.allclose(feature_map, np.array([[0.36689668, 0.36689668],
                                            [-0.00298354, -0.00298354]]),
                    atol=1e-6)